### ISSUE TITLE
Running tests locally

### ISSUE THREAD

**Issue by jayvdb** [al45tair/dmgbuild#33] opened 2021-03-29 08:14 UTC
I see the tests pass on CI.

On Big Sur (11.2.3 (20D91)) I am seeing a failure in `test_sample_settings`.

```py
        if options['license']:
            ret, output = hdiutil('unflatten', '-quiet', filename, plist=False)

            if ret:
>               raise DMGError('Unable to unflatten to add license')
E               dmgbuild.core.DMGError: Unable to unflatten to add license

dmgbuild/core.py:648: DMGError
--------------------------------- Captured stderr call ---------------------------------
ditto: /Volumes/Test/TextEdit.app/Contents: Operation not permitted
hdiutil: unflatten: verb not recognized
Usage: /usr/bin/hdiutil <verb> <options>
<verb> is one of the following:
help
attach
detach
eject
verify
create
compact
convert
burn
info
checksum
chpass
erasekeys
imageinfo
isencrypted
makehybrid
mount
mountvol
unmount
plugins
resize
segment
pmap
udifderez
udifrez
================================== short test summary info ==================================
FAILED tests/test_samples.py::test_sample_settings - dmgbuild.core.DMGError: Unable to unflatten to add license
================================= 1 failed, 1 passed in 12.63s ================================
```

**Comment by al45tair** [comment] 2021-05-16 11:53
This is a duplicate of #29.

**Closed by al45tair** 2021-05-16 11:53 UTC
